In [1]:
import mintapi

In [2]:
mint = mintapi.Mint(
    'joe83830@gmail.com',  # Email used to log in to Mint
    'Joe89623@CT',  # Your password used to log in to mint
    # Optional parameters
    mfa_method='sms',  # Can be 'sms' (default) or 'email'.
                       # if mintapi detects an MFA request, it will trigger the requested method
                       # and prompt on the command line.
    headless=False,  # Whether the chromedriver should work without opening a
                     # visible window (useful for server-side deployments)
    mfa_input_callback=None,  # A callback accepting a single argument (the prompt)
                              # which returns the user-inputted 2FA code. By default
                              # the default Python `input` function is used.
    session_path=None, # Directory that the Chrome persistent session will be written/read from.
                       # To avoid the 2FA code being asked for multiple times, you can either set
                       # this parameter or log in by hand in Chrome under the same user this runs
                       # as.
    imap_account=None, # account name used to log in to your IMAP server
    imap_password=None, # account password used to log in to your IMAP server
    imap_server=None,  # IMAP server host name
    imap_folder='INBOX',  # IMAP folder that receives MFA email
  )

/Users/joeliao/anaconda3/lib/python3.6/site-packages/mintapi/api.py:259: UserWarning: Giving up on handling MFA. Please complete the MFA process manually in the browser.
  warnings.warn("Giving up on handling MFA. Please complete "

In [3]:
overview = mint.get_accounts()

In [4]:
overview[1]

{'linkedAccountId': None,
 'accountName': 'Bank of America Cash Rewards World Mastercard Card ',
 'addAccountDate': 1554843748000,
 'fiLoginDisplayName': 'Bank of America',
 'ccAggrStatus': 0,
 'dueDate': '04/20/2019',
 'exclusionType': '0',
 'linkedAccount': None,
 'isHiddenFromPlanningTrends': True,
 'isTerminal': True,
 'linkCreationTime': None,
 'isActive': True,
 'accountStatus': '1',
 'accountSystemStatus': 'ACTIVE',
 'lastUpdated': 1555463908000,
 'fiLastUpdated': 1555463908000,
 'yodleeAccountNumberLast4': '6861',
 'isError': False,
 'fiName': 'Bank of America',
 'isAccountNotFound': False,
 'klass': 'credit',
 'possibleLinkAccounts': [],
 'lastUpdatedInString': '5 minutes',
 'accountTypeInt': 3,
 'currency': 'USD',
 'id': 10333543,
 'isHostAccount': False,
 'value': -155.75,
 'fiLoginId': 4969958,
 'usageType': None,
 'interestRate': None,
 'accountType': 'credit',
 'currentBalance': 155.75,
 'fiLoginStatus': 'OK',
 'isAccountClosedByMint': False,
 'userName': None,
 'yodleeName': 'Bank of America Cash Rewards World Mastercard Card ',
 'closeDate': 1555463907000,
 'linkStatus': 'NOT_LINKED',
 'dueAmt': 359.43,
 'accountId': 10333543,
 'isClosed': False,
 'fiLoginUIStatus': 'OK',
 'yodleeAccountId': 75406744741,
 'name': 'Bank of America Cash Rewards World Mastercard Card ',
 'status': '1',
 'addAccountDateInDate': datetime.datetime(2019, 4, 9, 17, 2, 28),
 'closeDateInDate': datetime.datetime(2019, 4, 16, 21, 18, 27),
 'fiLastUpdatedInDate': datetime.datetime(2019, 4, 16, 21, 18, 28),
 'lastUpdatedInDate': datetime.datetime(2019, 4, 16, 21, 18, 28)}

In [16]:
trans = mint.get_transactions()

RuntimeError: Error requesting 'https://mint.intuit.com/transactionDownload.event', content type 'text/html; charset=UTF-8' does not match 'text/csv'

In [6]:
bud = mint.get_budgets()

In [7]:
bud['spend'][3]

{'st': 2,
 'ramt': 0,
 'isIncome': False,
 'isTransfer': False,
 'isExpense': True,
 'amt': 19.38,
 'pid': 7,
 'type': 0,
 'bgt': 20.0,
 'rbal': 0.62,
 'ex': False,
 'cat': 'Coffee Shops',
 'id': 122849821,
 'catTypeFilter': 'Personal'}

In [8]:
all_cat = set()
coffee_sum = 0
coffee_idx = []
coffee_brk = []

In [9]:
for i in range(trans.shape[0]):
    all_cat.add(trans.iloc[i][5])
    if trans.iloc[i]['category'] == 'restaurants':
        coffee_sum += trans.iloc[i]['amount']
        coffee_idx.append(i)
        coffee_brk.append(trans.iloc[i]['amount'])

In [10]:
all_cat

{'air travel',
 'alcohol & bars',
 'atm fee',
 'business services',
 'cash & atm',
 'charity',
 'check',
 'clothing',
 'coffee shops',
 'credit card payment',
 'doctor',
 'electronics & software',
 'eyecare',
 'fast food',
 'federal tax',
 'fees & charges',
 'financial advisor',
 'food & dining',
 'gas & fuel',
 'gift',
 'groceries',
 'hair',
 'health insurance',
 'hotel',
 'income',
 'interest income',
 'laundry',
 'mortgage & rent',
 'movies & dvds',
 'music',
 nan,
 'newspapers & magazines',
 'pharmacy',
 'public transportation',
 'rental car & taxi',
 'restaurants',
 'service fee',
 'shipping',
 'shopping',
 'transfer',
 'travel',
 'vacation'}

In [11]:
trans

,date,description,original_description,amount,transaction_type,category,account_name,labels,notes
0,2019-04-16,New York Medical,NEW YORK MEDICAL IMA,37.05,debit,doctor,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
1,2019-04-16,GrubHub,GRUBHUB*WHOLESOMEFACTO,13.10,debit,food & dining,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
2,2019-04-16,UPS,UPS*INTERNETSHIPWAYBIL,17.98,debit,shipping,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
3,2019-04-16,Duane Reade,DUANE READE #14386,10.89,debit,pharmacy,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
4,2019-04-16,UPS,UPS*INTERNETSHIPWAYBIL,9.90,debit,shipping,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
5,2019-04-16,Transfer from CHASE SAVINGS,ONLINE TRANSFER FROM SAV ...0615TRANSACTION#: ...,500.00,credit,transfer,CHASE COLLEGE,NaN,NaN
6,2019-04-16,Deserve Entry Descr,ORIG CO NAME:DESERVE INC COENTRY DESCR:PA...,27.75,debit,NaN,CHASE COLLEGE,NaN,NaN
7,2019-04-16,Transfer to CHASE COLLEGE,ONLINE TRANSFER TO CHK ...0515 TRANSACTION#: 8...,500.00,debit,transfer,CHASE SAVINGS,NaN,NaN
8,2019-04-15,Lyft,LYFT *RIDE SAT 12PM 8552800278 CA,13.85,debit,rental car & taxi,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
9,2019-04-15,Sq Ume,SQ *SQ *UME Brooklyn NY,105.07,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
10,2019-04-15,Lyft,LYFT *RIDE SUN 4PM 8552800278 CA,14.39,debit,rental car & taxi,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
11,2019-04-15,Angels,ANGELS SHARE,22.44,debit,clothing,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
12,2019-04-15,Transfer from Rewards Savings,PAYMENT,481.71,credit,credit card payment,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
13,2019-04-15,Transfer to Bank of America Cash Rewards World...,Bank of America Credit Card Bill Payment,481.71,debit,credit card payment,Rewards Savings,NaN,NaN
14,2019-04-15,Deserve Web Id,DESERVE INC PAYMENT 384591 WE...,307.88,debit,NaN,CHASE COLLEGE,NaN,NaN
15,2019-04-15,Wall Street Journal,D J*WALL-ST-JOURNAL 800-568-7625MA 04/13,4.00,debit,newspapers & magazines,CHASE COLLEGE,NaN,NaN
16,2019-04-12,Griffis Faculty Club Inc,GRIFFIS FACULTY CLUB NEW YORK NY,5.49,debit,restaurants,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
17,2019-04-12,Wisalkhan Ca,PAYPAL *WISALKHAN 4029357733 CA,439.98,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
18,2019-04-11,Transfer from Rewards Savings,PAYMENT,539.18,credit,credit card payment,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
19,2019-04-11,MTA,MTA*METROCARD MACHINE NEW YORK NY,26.25,debit,public transportation,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
20,2019-04-11,Tidal Fl,TIDAL 8448784325 FL,9.99,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
21,2019-04-11,Transfer to Bank of America Cash Rewards World...,BANK OF AMERICA CREDIT CARD Bill Payment,539.18,debit,credit card payment,Rewards Savings,NaN,NaN
22,2019-04-11,Deserve Web Id,DESERVE INC PAYMENT 384591 WE...,69.34,debit,NaN,CHASE COLLEGE,NaN,NaN
23,2019-04-11,Mgp Chrono Gmbh,MGP*CHRONO24 GMBH TC 12 LUXEMBOURG 0...,3624.00,debit,NaN,CHASE COLLEGE,NaN,NaN
24,2019-04-11,Spotify,Spotify USA 877-7781161 NY04/11,4.99,debit,music,CHASE COLLEGE,NaN,NaN
25,2019-04-10,Deserve Web Id,DESERVE INC PAYMENT 384591 WE...,45.90,debit,NaN,CHASE COLLEGE,NaN,NaN
26,2019-04-10,Robinhood Funds Ppd,ROBINHOOD FundsPPD ID: 1464364776,1079.11,debit,NaN,CHASE COLLEGE,NaN,NaN
27,2019-04-10,Robinhood Funds Ppd,ROBINHOOD FundsPPD ID: 1464364776,335.55,debit,NaN,CHASE COLLEGE,NaN,NaN
28,2019-04-10,Robinhood Funds Ppd,ROBINHOOD FundsPPD ID: 1464364776,1361.24,debit,NaN,CHASE COLLEGE,NaN,NaN
29,2019-04-10,Robinhood Funds Ppd,ROBINHOOD FundsPPD ID: 1464364776,895.30,debit,NaN,CHASE COLLEGE,NaN,NaN
...,...,...,...,...,...,...,...,...,...
339,2019-02-08,Cornell Tech,CORNELL TECH NEW YORK NY,7.00,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
340,2019-02-08,GrubHub,GRUBHUBPICCOLOTRATTOR GRUBHUB.COM NY 0...,27.42,debit,food & dining,CHASE COLLEGE,NaN,NaN
341,2019-02-07,Fuji East,FUJI EAST NEW YORK NY,30.00,debit,restaurants,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
342,2019-02-07,Gristedes,GRISTEDES # 512 NEW YORK NY,7.42,debit,groceries,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
343,2019-02-06,Transfer from Rewards Savings,PAYMENT,913.88,credit,credit card payment,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
344,2019-02-06,Cornell Tech,CORNELL TECH NEW YORK NY,9.00,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
345,2019-02-06,Aetna,AETNA-866-36-VITAL 866-368-4825 TX,7.99,debit,health insurance,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
346,2019-02-06,Amazon,AMZN MKTP US*MB38S32M2 AMZN.COM/BILLWA,29.79,debit,shopping,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
347,2019-02-06,Transfer to Bank of America Cash Rewards World...,Bank of America Credit Card Bill Payment,913.88,debit,credit card payment,Rewards Savings,NaN,NaN
348,2019-02-06,GrubHub,GRUBHUBVIDALISPIZZA GRUBHUB.COMNY 02/06,37.04,debit,food & dining,CHASE COLLEGE,NaN,NaN
349,2019-02-05,Cornell Tech,CORNELL TECH NEW YORK NY,6.97,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
350,2019-02-05,Interest,INTEREST PAYMENT,0.63,credit,interest income,CHASE SAVINGS,NaN,NaN
351,2019-02-04,Amazon web services,Amazon web services aws.amazon.co WA 0...,21.09,debit,electronics & software,CHASE COLLEGE,NaN,NaN
352,2019-02-01,Netflix,NETFLIX.COM Amsterdam01/31 TW Dollar 390.00 X...,12.71,debit,movies & dvds,CHASE COLLEGE,NaN,NaN
353,2019-02-01,Netflix,FOREIGN EXCHANGE RATE ADJUSTMENTFEE 01...,0.38,debit,movies & dvds,CHASE COLLEGE,NaN,NaN
354,2019-01-31,Soylent Ca,SOYLENT 8447695368 CA,37.05,debit,groceries,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
355,2019-01-30,Foreign Transaction Fee,FOREIGN TRANSACTION FEE C_FEES,25.33,debit,service fee,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
356,2019-01-30,Expedia,EXPEDIA 7408803115163 EXPEDIA.CO.TWESP,844.53,debit,travel,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
357,2019-01-29,Federal Withholding,Federal Withholding,0.12,debit,federal tax,Rewards Savings,NaN,NaN
358,2019-01-29,Interest Earned,Interest Earned,0.50,credit,interest income,Rewards Savings,NaN,NaN
359,2019-01-22,Transfer to Bank of America Cash Rewards World...,Bank of America Credit Card Bill Payment,123.71,debit,credit card payment,Rewards Savings,NaN,NaN
360,2019-01-19,Transfer from Rewards Savings,PAYMENT,123.71,credit,credit card payment,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
361,2019-01-14,17life.com Taipei,17Life.com TAIPEI,13.07,debit,NaN,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
362,2019-01-14,Foreign Transaction Fee,FOREIGN TRANSACTION FEE C_FEES,0.39,debit,service fee,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
363,2019-01-14,Wall Street Journal,D J*WALL-ST-JOURNAL 800-568-7625MA 01/13,4.00,debit,newspapers & magazines,CHASE COLLEGE,NaN,NaN
364,2019-01-12,Amazon,AMZN DIGITAL*MB7SU0AH1 888-802-3080 WA,5.99,debit,shopping,Bank of America Cash Rewards World Mastercard ...,NaN,NaN
365,2019-01-11,Spotify,Spotify USA 646-8375380 NY01/11,4.99,debit,music,CHASE COLLEGE,NaN,NaN
366,2019-01-03,Amazon web services,Amazon web services aws.amazon.co WA 0...,21.09,debit,electronics & software,CHASE COLLEGE,NaN,NaN
367,2019-01-02,Netflix,FOREIGN EXCHANGE RATE ADJUSTMENTFEE 12...,0.38,debit,movies & dvds,CHASE COLLEGE,NaN,NaN
368,2019-01-02,Netflix,NETFLIX.COM Amsterdam12/31 TW Dollar 390.00 X...,12.75,debit,movies & dvds,CHASE COLLEGE,NaN,NaN

In [15]:
trans.iloc[15]['date']

Timestamp('2019-04-15 00:00:00')

In [72]:
coffee_sum

1159.72

In [56]:
coffee_brk

[3000.0]

In [58]:
trans.iloc[135]

date                                         2019-03-19 00:00:00
description                                  Robinhood Funds Ppd
original_description    ROBINHOOD        FundsPPD ID: 1464364776
amount                                                      3000
transaction_type                                           debit
category                                         mortgage & rent
account_name                                       CHASE COLLEGE
labels                                                       NaN
notes                                                        NaN
Name: 135, dtype: object